services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db: