services:

  pg:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - app:/data/postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    volumes:
      - app:/data/redis

  app:
    container_name: app
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 9999:8000
    depends_on:
      - pg
      - redis
    command: ["/app/docker/app.sh"]

  celery:
    container_name: celery
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    volumes:
      - app:/data/celery

  flower:
    container_name: flower
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
    volumes:
      - app:/data/flower

volumes:
  app: