services:
  pg:
    image: postgres
    container_name: postgres
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - fastapi_app:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    env_file:
      - backend/.env
    ports:
      - "6379:6379"
    volumes:
      - fastapi_app:/data/redis
    networks:
      - app-network

  app:
    container_name: app
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 9999:8000
    depends_on:
      - pg
      - redis
    command: ["/app/docker/app.sh"]
    networks:
      - app-network

  celery:
    container_name: celery
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    volumes:
      - fastapi_app:/data/celery
    networks:
      - app-network

  flower:
    container_name: flower
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
    volumes:
      - fastapi_app:/data/flower
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  fastapi_app: